services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1.amd64
    platform: linux/amd64
    container_name: weather_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    platform: linux/amd64
    container_name: weather_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  redis:
    image: redis:8.0.0
    container_name: weather_redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: weather_api
    depends_on:
      - redis
      - kafka
    ports:
      - "8000:5000"       # host:container
    env_file:
      - .env              # loads API_KEY, etc.
    environment:
      REDIS_HOST: redis   # for redis.Redis(host=os.getenv("REDIS_HOST"), ...)
      KAFKA_BOOTSTRAP: kafka:9092

  alerts:
    build:
      context: ./alerts
      dockerfile: Dockerfile.alerts
    container_name: weather_alerts
    depends_on:
      - kafka
    env_file:
      - .env